logging:
  level:
    root: TRACE
server:
  port: 8081

spring:
  profiles:
    active: mongo-to-pg,postgresql,mongodb
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: transactions-java-server
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://keycloak:8082/auth/realms/transactions
# TODO : Add to comment because bean OAuth2AuthorizedClientManager is not loaded in application context
#  main:
#    web-application-type: NONE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions-dev
      uri: mongodb://sync-dev-transactions-mongo-db-6:27017/transactions-staging
  flyway:
    enabled: true
    locations: classpath:db/migration/sync
  datasource:
    url: jdbc:postgresql://dev-transactions-sync-postgresql:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_PASSWORD} 
  elasticsearch:
    rest:
      uris: http://localhost:9200

es:
  index: transactiondev
  hostname: localhost:9200

client:
  transactions:
    base-url: http://localhost:8080
