server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions-dev
      uri: mongodb://localhost:27017/transactions-dev
  elasticsearch:
    rest:
      uris: http://localhost:9200

es:
  index: transactiondev
  hostname: localhost:9200

