server:
  port: 8080

spring:
  data:
    mongodb:
      host: transactions-mongo-db
      port: 27017
      database: transactions-staging
  elasticsearch:
    rest:
      uris: http://transactions-elastic-search:9200

es:
  index: transactionsstaging
  hostname: transactions-elastic-search:9200

