name: deploy

on:
  push:
  release:
    types: [published]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Create docker image tag name with github release name
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build image
        run: docker build . --file Dockerfile --tag jugirard/transactions-sync-process:${{steps.vars.outputs.tag}} --tag jugirard/transactions-sync-process:latest
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push jugirard/transactions-sync-process:${{steps.vars.outputs.tag}}
      - name: Push Docker Image latest tag
        run: docker push jugirard/transactions-sync-process:latest
      - name: Docker logout
        run: docker logout

