name: Maven Release Prepare

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (ex: 1.0.0)'
        required: true
      nextVersion:
        description: 'Prochaine version de développement (ex: 1.0.1-SNAPSHOT)'
        required: true

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Prepare Release
        run: |
          mvn -B release:prepare \
            -DreleaseVersion=${{ github.event.inputs.tag }} \
            -DdevelopmentVersion=${{ github.event.inputs.nextVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Perform Release
        run: mvn -B release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
